gitlabUrl: https://gitlab.com

## Concurrency and global settings
concurrent: 3
checkInterval: 30

rbac:
  create: true

serviceAccount:
  create: true

runners:
  # Using the secret we created
  secret: gitlab-runner-secret
  
  config: |
    [[runners]]
      name = "oke-runner-arm64"
      executor = "kubernetes"
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:22.04"
        privileged = true
        helper_image = "registry.gitlab.com/gitlab-org/gitlab-runner/gitlab-runner-helper:arm64-v18.11.3"
        cpu_request = "100m"
        memory_request = "128Mi"
        cpu_limit = "1000m"
        memory_limit = "512Mi"
        # OKE Performance Fix for DinD
        [[runners.kubernetes.volumes.empty_dir]]
          name = "docker-data"
          mount_path = "/var/lib/docker"
      [runners.cache]
        Type = "s3"
        Path = "gitlab-runner"
        Shared = true
        [runners.cache.s3]
          ServerAddress = "OCI_NAMESPACE_PLACEHOLDER.compat.objectstorage.us-ashburn-1.oraclecloud.com"
          BucketName = "gitlab-runner-cache"
          BucketLocation = "us-ashburn-1"
          AuthenticationType = "iam"

## Security Context for the runner manager
securityContext:
  allowPrivilegeEscalation: true
  readOnlyRootFilesystem: false
  privileged: true
